[build]
  command = "npm run build"
  functions = "src/"

[[redirects]]
  from = "/_*"
  to = "/_:splat"
  status = 200
  force = true

[[redirects]]
  from = "/:code"
  to = "/_redirect?short=:code"
  status = 301
  force = true
